version: "2"

services:
    nginx:
        image: nginx
        ports:
            - "${SERVER_PORT}:80"
        links:
            - phpfpm:phpfpm
        volumes:
            - ./server/logs/:/var/log/nginx/
            - ./server/app.conf:/etc/nginx/conf.d/default.conf
            - ./app:/app

    phpfpm:
        image: php:fpm
        ports:
            - "9000:9000"
        volumes:
            - ./app:/app

    db:
        image: mysql
        ports:
            - '${MYSQL_PORT}:3306'
        volumes:
            - ./db-data:/var/lib/mysql
        environment:
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "${PHPMYADMIN_PORT}:80"
        links:
            - db:db
        environment:
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            PMA_HOST: db