
# Replace the content of the docker-compose.yml with the autogenerated warning message
echo "#######################################################" > "docker-compose.yml"
echo "# This file is autogenerated, avoid to lose your      #" >> "docker-compose.yml"
echo "# configurations change the \`docker-compose.stub.yml\` #" >> "docker-compose.yml"
echo "# and run the \`init.sh\` to generate this file         #" >> "docker-compose.yml"
echo "#######################################################" >> "docker-compose.yml"
echo "" >> "docker-compose.yml"

# Append the environment substitution of variables on docker-compos.stub.yml
source ./env.sh; envsubst < "docker-compose.stub.yml" >> "docker-compose.yml";
